# Generated by Django 4.2.7 on 2023-12-17 18:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meteo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dht2Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_date', models.DateTimeField(auto_now_add=True, db_column='date time')),
                ('date', models.DateField(default=datetime.date.today)),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Dht2History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('min_temperature', models.FloatField()),
                ('max_temperature', models.FloatField()),
                ('min_humidity', models.FloatField()),
                ('max_humidity', models.FloatField()),
            ],
        ),
        migrations.RenameModel(
            old_name='DhtData',
            new_name='Dht1Data',
        ),
        migrations.RenameModel(
            old_name='DhtHistory',
            new_name='Dht1History',
        ),
    ]
